# -*- coding: utf-8 -*-
"""Depressive-tweet-search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cpZaA5DbpNi0P5oI_i2uRFqcEBuBiPI

## Scrape Depressive tweets from Twitter for 2020

I would like to gather data from twitter based on depressive hashtags, such as #depressed, #anxiety, #depression, #suicide, #mentalhealth, #loneliness, #hopelessness, #itsokaynottobeokay. Then apply various techniques to remove non-depressive messages The result of this script will provide a dataset that contains a filtered collection of tweets that are potentially depressive. The script also removes all hashtags from the tweets, so that the machine learning model cannot cheat by just looking for depressive hashtags. The final dataset will be manually reviewed and labelled, so that both the depressive and non-depressive messages within it will be correctly marked.
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U git+https://github.com/cyxv/twint.git@master

!pip3 install -qq twint
!pip install -qq whatthelang

# Import Library
import twint
import nest_asyncio
nest_asyncio.apply()
import pandas as pd
import re

# Instantiate and configure the twint-object
c = twint.Config()
c.Store_object = True
c.Pandas =True
c.Search = "#depressed"
c.Limit = 100000

# Run search
twint.run.Search(c)

# Quick check
twint.storage.panda.Tweets_df.head()

# Cleanup
tweets_depressed = twint.storage.panda.Tweets_df.drop_duplicates(subset=['id'])

# Reindex
tweets_depressed.index = range(len(tweets_depressed))

# Remove non-english
from whatthelang import WhatTheLang
wtl = WhatTheLang()

# This function makes easy to handle exceptions (e.g. no text where text should be)
# not really needed but can be useful 

def detect_lang(text):
    try: 
        return wtl.predict_lang(text)
    except Exception:
        return 'exp'

# Commented out IPython magic to ensure Python compatibility.
# # Added performance measure here...you can leave teh %%time line out
# 
# %%time
# 
# tweets_depressed['lang'] = tweets_depressed['tweet'].map(lambda t: detect_lang(t))

# keep only english

tweets_depressed = tweets_depressed[tweets_depressed.lang == 'en']

tweets_depressed

tweets_depressed_new = tweets_depressed[['id','tweet']]

tweets_depressed_new

# Done

tweets_depressed_new.to_csv('/content/drive/MyDrive/NLP/Depression_Detection/tweets_depressed_new.csv')

